
export const LOGIN_REQUEST= 'LOGIN_REQUEST'
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS'
export const LOGIN_FAILED= 'LOGIN_FAILED'
export const LOGIN_RESET= 'LOGIN_RESET'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const REGISTER_REQUEST= 'REGISTER_REQUEST'
export const REGISTER_SUCCESS= 'REGISTER_SUCCESS'
export const REGISTER_FAILED= 'REGISTER_FAILED'
export const STORE_SUCCESS='STORE_SUCCESS'
export const STORE_FAILURE='STORE_FAILURE'

export const FETCH_FORMATIONS_SUCCESS='FETCH_FORMATIONS_SUCCESS'
export const FETCH_FORMATIONS_ERROR='FETCH_FORMATIONS_ERROR'
export const FETCH_GROUPE ='FETCH_GROUPE'
export const FETCH_GROUPE_ERROR='FETCH_GROUPE_ERROR'

    